# Generated by Django 4.2.5 on 2023-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default="No Content"),
        ),
        migrations.AlterField(
            model_name="post", 
            name="title", 
            field=models.CharField(max_length=255),
        ),
    ]
