# Generated by Django 5.0 on 2024-01-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pas de titre', max_length=150)),
                ('desc', models.TextField(default='Pas de description')),
                ('favorite', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='slug')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medecine',
                'verbose_name_plural': 'Medecines',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField()),
                ('pseudo', models.CharField(unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pas de titre', max_length=150)),
                ('desc', models.TextField(default='Pas de description')),
                ('desc_sound', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecine.medecine')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.AddField(
            model_name='medecine',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='medecines', to='medecine.patient'),
        ),
    ]
