# Generated by Django 5.0 on 2024-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecine',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medecine',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='medecine',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
