# Generated by Django 5.0 on 2024-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0002_alter_medecine_desc_alter_medecine_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
