# Generated by Django 5.0 on 2024-01-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0003_alter_medecine_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
