# Generated by Django 5.0 on 2024-01-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0004_delete_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecine',
            old_name='favorite',
            new_name='online',
        ),
    ]
