# Generated by Django 5.0 on 2024-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0005_rename_favorite_medecine_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
