# Generated by Django 5.0 on 2024-01-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0006_alter_medecine_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
