# Generated by Django 5.0 on 2024-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0007_alter_medecine_img'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterField(
            model_name='medecine',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='medecines', to='patient.patient'),
        ),
    ]
