# Generated by Django 5.0 on 2024-01-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecine', '0004_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pas de titre', max_length=150)),
                ('desc', models.TextField(default='Pas de description')),
                ('desc_sound', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecine.medecine')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
