# Generated by Django 5.0 on 2024-01-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_alter_faq_desc_alter_faq_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
